'use client';
import { Loader2, Search } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { StatusBadge } from '@/components/shared/StatusBadge';
export const unwrap=(response:any)=>{const data=response?.data?.data;return Array.isArray(data)?data:data?.items||data||[]};
export const number=(value:any,digits=2)=>new Intl.NumberFormat('en-IN',{maximumFractionDigits:digits}).format(Number(value||0));
export const money=(value:any)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(value||0));
export const date=(value:any)=>value?new Intl.DateTimeFormat('en-IN',{dateStyle:'medium'}).format(new Date(value)):'—';
export const nameOf=(rows:any[],id?:string)=>rows.find(row=>row.id===id)?.name||rows.find(row=>row.id===id)?.sku||id||'—';
export function Field({label,required,children,hint}:{label:string;required?:boolean;children:React.ReactNode;hint?:string}){return <div className="space-y-1.5"><Label className="text-xs font-semibold text-[#46524b]">{label}{required&&<span className="ml-1 text-red-500">*</span>}</Label>{children}{hint&&<p className="text-[11px] text-[#7d8982]">{hint}</p>}</div>}
export function NativeSelect({value,onChange,placeholder,rows,getLabel,disabled}:{value:string;onChange:(value:string)=>void;placeholder:string;rows:any[];getLabel?:(row:any)=>string;disabled?:boolean}){return <select disabled={disabled} value={value||''} onChange={e=>onChange(e.target.value)} className="h-10 w-full rounded-md border border-[#d8dedb] bg-white px-3 text-sm text-[#243029] outline-none transition focus:border-[#2f8f5b] focus:ring-2 focus:ring-[#2f8f5b]/10 disabled:bg-[#f2f4f3]"><option value="">{placeholder}</option>{rows.map(row=><option key={row.id} value={row.id}>{getLabel?getLabel(row):row.name||row.code||row.sku||row.id}</option>)}</select>}
export function SearchBox({value,onChange,placeholder='Search records…'}:{value:string;onChange:(value:string)=>void;placeholder?:string}){return <div className="relative w-full sm:w-72"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#87918c]"/><Input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-9 pl-9"/></div>}
export function LoadingBlock({label='Loading manufacturing data…'}:{label?:string}){return <div className="flex min-h-48 items-center justify-center gap-2 rounded-xl border border-[#e1e6e3] bg-white text-sm text-[#68746d]"><Loader2 className="h-4 w-4 animate-spin text-[#258653]"/>{label}</div>}
export function EmptyBlock({title,text}:{title:string;text:string}){return <div className="rounded-xl border border-dashed border-[#cfd8d3] bg-[#fafcfb] px-5 py-12 text-center"><p className="font-medium text-[#35423b]">{title}</p><p className="mx-auto mt-1 max-w-lg text-sm text-[#758079]">{text}</p></div>}
export function Metric({label,value,tone='green',note}:{label:string;value:React.ReactNode;tone?:'green'|'blue'|'amber'|'red'|'slate';note?:string}){const tones:any={green:['bg-[#2c9a61]','text-[#187a48]'],blue:['bg-[#3388c7]','text-[#246fa7]'],amber:['bg-[#d79a32]','text-[#98691e]'],red:['bg-[#cb4f4f]','text-[#a63f3f]'],slate:['bg-[#68756e]','text-[#56625b]']};return <div className="rounded-xl border border-[#e0e6e2] bg-white p-4 shadow-[0_1px_4px_rgba(16,24,40,0.035)]"><div className={`mb-3 h-1.5 w-10 rounded-full ${tones[tone][0]}`}/><p className="text-xs font-semibold uppercase tracking-wide text-[#77827c]">{label}</p><p className={`mt-1 text-2xl font-semibold ${tones[tone][1]}`}>{value}</p>{note&&<p className="mt-1 text-xs text-[#89928d]">{note}</p>}</div>}
export function Progress({value,max,tone='green'}:{value:number;max:number;tone?:'green'|'blue'|'amber'|'red'}){const pct=max>0?Math.min(100,Math.max(0,value/max*100)):0;const color={green:'bg-[#2c9a61]',blue:'bg-[#3388c7]',amber:'bg-[#d79a32]',red:'bg-[#cb4f4f]'}[tone];return <div className="h-2 overflow-hidden rounded-full bg-[#edf0ee]"><div className={`h-full rounded-full ${color}`} style={{width:`${pct}%`}}/></div>}
export function Status({value}:{value:string}){return <StatusBadge status={value||'DRAFT'}/>}
