'use client';
import { Factory } from 'lucide-react';
import { ManufacturingBomsPage, ManufacturingRoutingsPage } from './ManufacturingStructures';
import { ManufacturingMasterPage } from './ManufacturingMasters';
import { ManufacturingWorkOrdersPage, ManufacturingJobCardsPage } from './ManufacturingExecution';
import { ManufacturingDashboardPage, ManufacturingReportsPage, ManufacturingShopfloorPage } from './ManufacturingInsights';

export type ManufacturingPageKind = 'dashboard'|'boms'|'routings'|'work-centers'|'machines'|'operations'|'work-orders'|'job-cards'|'shopfloor'|'reports';
const copy: Record<ManufacturingPageKind, [string, string]> = {
  dashboard:['Production control','Plan, monitor and resolve today’s factory execution from one place.'], boms:['Bills of materials','Engineer revision-controlled, multi-level product structures with cost and where-used visibility.'], routings:['Production routings','Define operation sequence, capacity, time standards and inspection gates.'], 'work-centers':['Work centers','Configure available capacity, efficiency and absorption rates for production areas.'], machines:['Machines','Manage machine assignment, live state, capacity and maintenance dates.'], operations:['Operation library','Maintain reusable manufacturing, assembly, inspection and outsourced operations.'], 'work-orders':['Work orders','Control material, WIP, production receipt, scrap, cost and closure end to end.'], 'job-cards':['Job cards','Run operation-level production, downtime, rejection and first-piece controls.'], shopfloor:['Shop-floor terminal','A scan-first, touch-friendly workspace for operators and supervisors.'], reports:['Manufacturing analytics','Review output, WIP, utilisation, OEE, losses, cost and productivity.'],
};
export function ManufacturingPage({kind}:{kind:ManufacturingPageKind}) { let content:React.ReactNode; if(kind==='boms')content=<ManufacturingBomsPage/>;else if(kind==='routings')content=<ManufacturingRoutingsPage/>;else if(['work-centers','machines','operations'].includes(kind))content=<ManufacturingMasterPage kind={kind as any}/>;else if(kind==='work-orders')content=<ManufacturingWorkOrdersPage/>;else if(kind==='job-cards')content=<ManufacturingJobCardsPage/>;else if(kind==='shopfloor')content=<ManufacturingShopfloorPage/>;else if(kind==='reports')content=<ManufacturingReportsPage/>;else content=<ManufacturingDashboardPage/>;return <section className="space-y-5"><header className="relative overflow-hidden rounded-xl border border-[#dfe5e2] bg-white px-5 py-5 shadow-[0_2px_10px_rgba(16,24,40,0.04)]"><div className="absolute inset-y-0 right-0 w-52 bg-gradient-to-l from-[#eaf5ef] to-transparent"/><div className="relative flex items-start gap-3"><div className="rounded-lg bg-[#e7f4ec] p-2.5 text-[#147a48]"><Factory className="h-5 w-5"/></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#147a48]">Manufacturing</p><h1 className="mt-0.5 text-2xl font-semibold tracking-tight text-[#18231e]">{copy[kind][0]}</h1><p className="mt-1 max-w-3xl text-sm text-[#66736c]">{copy[kind][1]}</p></div></div></header>{content}</section> }
