'use client';

import { useEffect, useState } from 'react';
import { PageHeader } from '@/components/shared/PageHeader';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import api from '@/lib/api';
import { showApiError, showApiSuccess } from '@/lib/apiError';

export default function CrmSettingsPage() {
  const [data, setData] = useState<any>({ reasons: [], tokens: [], integrations: [], scopes: [], templates: [], users: [], branches: [], defaultQueueUserId: '' });
  const [reason, setReason] = useState(''); const [tokenName, setTokenName] = useState('Website form'); const [source, setSource] = useState('WEBSITE'); const [issuedToken, setIssuedToken] = useState('');
  const [integration, setIntegration] = useState({ provider: 'GMAIL', account: '', secret: '' });
  const [scope, setScope] = useState({ userId: '', entity: 'LEAD', scope: 'OWN', branchId: '' });
  const [template, setTemplate] = useState({ name: '', subject: '', bodyHtml: '' });
  const load = async () => { try { const [a,b,c,d,e,f] = await Promise.all([api.get('/crm/lost-reasons?all=true'),api.get('/crm/capture-tokens'),api.get('/crm/integrations'),api.get('/crm/scope-rules'),api.get('/crm/email-templates'),api.get('/crm/configuration')]); setData({ reasons:a.data.data||[], tokens:b.data.data||[], integrations:c.data.data||[], scopes:d.data.data||[], templates:e.data.data||[], users:f.data.data?.users||[], branches:f.data.data?.branches||[], defaultQueueUserId:f.data.data?.defaultQueueUserId||'' }); } catch (err) { showApiError(err, 'Could not load CRM configuration'); } };
  useEffect(() => { load(); }, []);
  const action = async (operation: () => Promise<any>, message: string) => { try { await operation(); showApiSuccess(message); await load(); } catch (err) { showApiError(err, message); } };
  const userName = (id: string) => { const user = data.users.find((item: any) => item.id === id); return user ? `${user.firstName} ${user.lastName}` : id; };
  return <div><PageHeader title="CRM Configuration" description="Manage loss reasons, scope, queues, capture channels, templates, and provider accounts" />
    <div className="grid gap-4 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Mandatory loss reasons</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex gap-2"><Input value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="Budget unavailable"/><Button disabled={!reason.trim()} onClick={()=>action(()=>api.post('/crm/lost-reasons',{name:reason,appliesTo:'BOTH'}),'Loss reason added').then(()=>setReason(''))}>Add</Button></div>{data.reasons.map((item:any)=><div key={item.id} className="flex items-center justify-between rounded border p-2 text-sm"><span>{item.name} · {item.appliesTo}</span><Button size="sm" variant="ghost" onClick={()=>action(()=>api.patch(`/crm/lost-reasons/${item.id}`,{isActive:!item.isActive}),item.isActive?'Reason disabled':'Reason enabled')}>{item.isActive?'Disable':'Enable'}</Button></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Visibility scope</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={scope.userId} onValueChange={(v)=>setScope({...scope,userId:v})}><SelectTrigger><SelectValue placeholder="Select user"/></SelectTrigger><SelectContent>{data.users.map((u:any)=><SelectItem key={u.id} value={u.id}>{u.firstName} {u.lastName}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-2 gap-2"><Select value={scope.entity} onValueChange={(v)=>setScope({...scope,entity:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['LEAD','OPPORTUNITY','ACTIVITY'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={scope.scope} onValueChange={(v)=>setScope({...scope,scope:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['OWN','TEAM','BRANCH','ALL'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select></div>{scope.scope==='BRANCH'&&<Select value={scope.branchId} onValueChange={(v)=>setScope({...scope,branchId:v})}><SelectTrigger><SelectValue placeholder="Select branch"/></SelectTrigger><SelectContent>{data.branches.map((b:any)=><SelectItem key={b.id} value={b.id}>{b.code} · {b.name}</SelectItem>)}</SelectContent></Select>}<Button disabled={!scope.userId||(scope.scope==='BRANCH'&&!scope.branchId)} onClick={()=>action(()=>api.post('/crm/scope-rules',scope),'Scope saved')}>Save scope</Button>{data.scopes.map((item:any)=><div key={item.id} className="flex justify-between rounded border p-2 text-sm"><span>{userName(item.userId)} · {item.entity} · {item.scope}</span><Button size="sm" variant="ghost" onClick={()=>action(()=>api.delete(`/crm/scope-rules/${item.id}`),'Scope deleted')}>Delete</Button></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Default unmatched-lead queue</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={data.defaultQueueUserId} onValueChange={(v)=>setData({...data,defaultQueueUserId:v})}><SelectTrigger><SelectValue placeholder="Select queue owner"/></SelectTrigger><SelectContent>{data.users.map((u:any)=><SelectItem key={u.id} value={u.id}>{u.firstName} {u.lastName}</SelectItem>)}</SelectContent></Select><Button disabled={!data.defaultQueueUserId} onClick={()=>action(()=>api.put('/crm/configuration/default-queue',{userId:data.defaultQueueUserId}),'Default queue updated')}>Save default queue</Button></CardContent></Card>
      <Card><CardHeader><CardTitle>Public lead capture</CardTitle></CardHeader><CardContent className="space-y-3"><Input value={tokenName} onChange={(e)=>setTokenName(e.target.value)}/><Select value={source} onValueChange={setSource}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['WEBSITE','INDIA_MART','FACEBOOK_LEAD_ADS','WHATSAPP'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Button onClick={async()=>{try{const response=await api.post('/crm/capture-tokens',{name:tokenName,source});setIssuedToken(response.data.data.token);showApiSuccess('Capture token issued');await load();}catch(err){showApiError(err,'Could not issue token');}}}>Issue token</Button>{issuedToken&&<div className="break-all rounded bg-amber-50 p-3 text-xs"><b>Copy now:</b> {issuedToken}</div>}{data.tokens.map((item:any)=><div key={item.id} className="flex justify-between rounded border p-2 text-sm"><span>{item.name} · {item.source} · {item.isActive?'Active':'Revoked'}</span>{item.isActive&&<Button size="sm" variant="ghost" onClick={()=>action(()=>api.delete(`/crm/capture-tokens/${item.id}`),'Token revoked')}>Revoke</Button>}</div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Email templates</CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Template name" value={template.name} onChange={(e)=>setTemplate({...template,name:e.target.value})}/><Input placeholder="Subject" value={template.subject} onChange={(e)=>setTemplate({...template,subject:e.target.value})}/><Textarea placeholder="HTML or message body" value={template.bodyHtml} onChange={(e)=>setTemplate({...template,bodyHtml:e.target.value})}/><Button disabled={!template.name||!template.subject||!template.bodyHtml} onClick={()=>action(()=>api.post('/crm/email-templates',template),'Template created').then(()=>setTemplate({name:'',subject:'',bodyHtml:''}))}>Create template</Button>{data.templates.map((item:any)=><div key={item.id} className="flex justify-between rounded border p-2 text-sm"><span>{item.name} · {item.subject}</span><Button size="sm" variant="ghost" onClick={()=>action(()=>api.delete(`/crm/email-templates/${item.id}`),'Template disabled')}>Disable</Button></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Gmail, Outlook, IMAP and WhatsApp</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={integration.provider} onValueChange={(v)=>setIntegration({...integration,provider:v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['GMAIL','OUTLOOK','IMAP','WHATSAPP'].map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Input placeholder="Account email or phone" value={integration.account} onChange={(e)=>setIntegration({...integration,account:e.target.value})}/><Input type="password" placeholder="OAuth/access token or app password" value={integration.secret} onChange={(e)=>setIntegration({...integration,secret:e.target.value})}/><Button disabled={!integration.account||!integration.secret} onClick={()=>action(()=>api.post('/crm/integrations',{provider:integration.provider,account:integration.account,credentials:{secret:integration.secret}}),'Integration connected').then(()=>setIntegration({...integration,account:'',secret:''}))}>Connect</Button>{data.integrations.map((item:any)=><div key={item.id} className="flex justify-between rounded border p-2 text-sm"><span>{item.provider} · {item.account} · {item.status}</span>{item.status==='ACTIVE'&&<Button size="sm" variant="ghost" onClick={()=>action(()=>api.delete(`/crm/integrations/${item.id}`),'Integration disconnected')}>Disconnect</Button>}</div>)}</CardContent></Card>
    </div></div>;
}
